[workspace]
authors = ["kgarrels <kgarrels@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "gqrx"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
cmake = ">=4.4.3,<5"
gnuradio-soapy = ">=3.10.12.0,<4"
soapysdr-module-airspyhf = ">=0.2.0,<0.3"
soapysdr-module-airspy = ">=0.2.0,<0.3"
soapysdr-module-audio = ">=0.1.1,<0.2"
soapysdr-module-rtlsdr = ">=0.3.3,<0.4"
qt6-main = ">=6.11.1,<7"
soapysdr-module-uhd = ">=0.4.1,<0.5"
libboost-devel = ">=1.88.0,<2"
